[package]
name = "dispatch_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
geo = "0.32.0"
osmpbf = "0.3.8"
petgraph = "0.8.3"
rand = "0.10.0"
rand_distr = "0.6.0"
ratatui = "0.30.0"
rayon = "1.11.0"
rstar = "0.12.2"
rusqlite = "0.38.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.0.1"
